# docker-openresty .travis.yml
#
# Builds docker-openresty images on Travis CI
#
# https://travis-ci.com/github/openresty/docker-openresty
#
#
# Master will build with Docker tag:
#   openresty:<flavor>
#
# Releases should be tagged in git as:
#   <openresty-version>-<docker-version>
#
# This will build with Docker tags:
#   openresty:<openresty-version>-<docker-version>-<flavor>
#   openresty:<openresty-version>-<flavor>
#

os: linux
dist: focal
language: generic

services:
  - docker

stages:
  - build
  - manifest
  - build-fat
  - manifest-fat

before_script:
  - echo $DOCKER_PASSWORD > /tmp/docker.pass

jobs:
  include:
###############################################################################
# Build From Source Flavors
# These take longer to build and are put in their own jobs
###############################################################################

    - name: Build aarch64 Docker image for build-from-source flavors alpine
      stage: build
      arch: arm64
      script:
      - ./docker_build_and_push_flavor.sh alpine-aarch64 alpine/Dockerfile

    - name: Build amd64 Docker image for build-from-source flavors alpine
      stage: build
      arch: amd64
      script:
      - ./docker_build_and_push_flavor.sh alpine-amd64 alpine/Dockerfile

    - name: Build aarch64 Docker image for build-from-source flavor bionic
      arch: arm64
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh bionic-aarch64 bionic/Dockerfile

    - name: Build amd64 Docker image for build-from-source flavor bionic
      arch: amd64
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh bionic-amd64 bionic/Dockerfile

    - name: Build aarch64 Docker image for build-from-source flavor focal
      arch: arm64
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh focal-aarch64 focal/Dockerfile

    - name: Build amd64 Docker image for build-from-source flavor focal
      arch: amd64
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh focal-amd64 focal/Dockerfile

###############################################################################
# Build From OpenResty Upstream Flavors
# These are shorter to build are put in the same job (per architecture)
###############################################################################

    - name: Build aarch64 Docker image for upstream flavors
      arch: arm64
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh alpine-apk-aarch64 alpine-apk/Dockerfile
      - ./docker_build_and_push_flavor.sh amzn2-aarch64 centos/Dockerfile --build-arg RESTY_IMAGE_BASE=amazonlinux --build-arg RESTY_IMAGE_TAG=2 --build-arg RESTY_YUM_REPO="https://openresty.org/package/amazon/openresty.repo" --build-arg RESTY_RPM_DIST="amzn2" --build-arg RESTY_RPM_ARCH=aarch64
      - ./docker_build_and_push_flavor.sh centos-aarch64 centos/Dockerfile --build-arg RESTY_RPM_ARCH=aarch64
      - ./docker_build_and_push_flavor.sh centos7-aarch64 centos7/Dockerfile --build-arg RESTY_RPM_ARCH=aarch64
      - ./docker_build_and_push_flavor.sh fedora-aarch64 fedora/Dockerfile --build-arg RESTY_RPM_ARCH=aarch64
      - ./docker_build_and_push_flavor.sh buster-aarch64 buster/Dockerfile --build-arg RESTY_APT_REPO="http://openresty.org/package/arm64/debian"

    - name: Build amd64 Docker image for upstream flavors
      arch: amd64
      stage: build
      script:
      - ./docker_build_and_push_flavor.sh alpine-apk-amd64 alpine-apk/Dockerfile
      - ./docker_build_and_push_flavor.sh amzn2-amd64 centos/Dockerfile --build-arg RESTY_IMAGE_BASE=amazonlinux --build-arg RESTY_IMAGE_TAG=2 --build-arg RESTY_YUM_REPO="https://openresty.org/package/amazon/openresty.repo" --build-arg RESTY_RPM_DIST="amzn2"
      - ./docker_build_and_push_flavor.sh centos-amd64 centos/Dockerfile
      - ./docker_build_and_push_flavor.sh centos7-amd64 centos7/Dockerfile
      - ./docker_build_and_push_flavor.sh fedora-amd64 fedora/Dockerfile
      - ./docker_build_and_push_flavor.sh buster-amd64 buster/Dockerfile

###############################################################################
# Multi-arch manifests
###############################################################################

    # also master buster gets tagged "latest"
    - name: Create and push manifests for multi-arch images
      stage: manifest
      script:
      - ./docker_manifest.sh alpine      alpine-amd64      alpine-aarch64
      - ./docker_manifest.sh alpine-apk  alpine-apk-amd64  alpine-apk-aarch64
      - ./docker_manifest.sh amzn2       amzn2-amd64       amzn2-aarch64
      - ./docker_manifest.sh bionic      bionic-amd64      bionic-aarch64
      - ./docker_manifest.sh buster      buster-amd64      buster-aarch64
      - ./docker_manifest.sh centos      centos-amd64      centos-aarch64
      - ./docker_manifest.sh centos7     centos7-amd64     centos7-aarch64
      - ./docker_manifest.sh fedora      fedora-amd64      fedora-aarch64
      - ./docker_manifest.sh focal       focal-amd64       focal-aarch64
      - ./docker_tag_alias.sh centos centos-rpm
      - ./docker_tag_alias.sh fedora fedora-rpm
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin &&
          docker pull $DOCKER_ORG/openresty:buster &&
          docker tag $DOCKER_ORG/openresty:buster $DOCKER_ORG/openresty:latest &&
          docker push $DOCKER_ORG/openresty:latest ;
        fi

###############################################################################
# Build Derived ("fat") Flavors
# Built after other images
###############################################################################

    - name: Build aarch64 fat Docker image
      stage: build-fat
      arch: arm64
      script:
      - ./docker_build_and_push_flavor.sh buster-fat-aarch64 buster/Dockerfile.fat
      - ./docker_build_and_push_flavor.sh alpine-fat-aarch64 alpine/Dockerfile.fat

    - name: Build amd64 fat Docker image
      arch: amd64
      stage: build-fat
      script:
      - ./docker_build_and_push_flavor.sh buster-fat-amd64 buster/Dockerfile.fat
      - ./docker_build_and_push_flavor.sh alpine-fat-amd64 alpine/Dockerfile.fat

    - name: Create and push manifests for fat multi-arch images
      stage: manifest-fat
      script:
      - ./docker_manifest.sh buster-fat  buster-fat-amd64  buster-fat-aarch64
      - ./docker_manifest.sh alpine-fat  alpine-fat-amd64  alpine-fat-aarch64
