name: Build Docker Image

on:
#  push:
#    branches: [ main ]

  workflow_dispatch:
    inputs:
      system:
        description: 'focal alpine'
        required: true
        default: 'alpine' 
        type: choice
        options:
        - focal
        - alpine
        - alpine-fat

      version:
        description: 'Input Build Version'
        required: true
        default: ''
        type: string

  workflow_call:
    inputs:
      system:
        required: true
        type: string
      version:
        required: true
        type: string

  #schedule:
  #  - cron: '0 12 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare files
        run: |
          cp nginx.vh.default.conf ./${{ inputs.system }}
          cp nginx.conf ./${{ inputs.system }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.system }}
          push: true
          tags: |
            xiaomoy/openresty:${{ inputs.version }}
